public enum StatisticType
{
    TOTAL_KILL = 101,
    TOTAL_DEATH,
    TOTAL_SUICIDE,
    HIGHEST_KILL,
    HIGHEST_DEATH,
    CONSECUTIVE_KILL_COUNT,
    CONSECUTIVE_DEATH_COUNT,

    HIGHSCORE = 201,
    CUMULATIVE_SCORE,

    TOTAL_PLAYTIME = 301,
    CONTINUOUS_PLAYTIME,

    TOTAL_CRATE_PICKUP = 401,
}
